modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/ThexXTURBOXx/Reforged-Modernized/issues"
license = "GNU-GPL-v3"

[[mods]]
modId = "reforged"
version = "${version}"
displayName = "Reforged"
authors = "HyperSpeeed, Silvercatcher, SnowballFlame, Sunconure11"
description = '''
This mod is a rewrite of Reforged, which is a Rewrite of Balkon's Weapons mod, for modern versions of Minecraft.
'''
logoFile = "icon.png"
updateJSONURL = "https://raw.githubusercontent.com/ThexXTURBOXx/UpdateJSONs/master/reforged.json"

[[dependencies.reforged]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reforged]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reforged]]
modId = "architectury"
mandatory = true
versionRange = "[3.6.17,)"
ordering = "AFTER"
side = "BOTH"
