modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/ThexXTURBOXx/Reforged-Modernized/issues"
license = "GNU-GPL-v3"

[[mods]]
modId = "reforged"
version = "${version}"
displayName = "Reforged"
authors = "HyperSpeeed, Silvercatcher, SnowballFlame, Sunconure11"
description = '''
This mod is a rewrite of Reforged, which is a Rewrite of Balkon's Weapons mod, for modern versions of Minecraft.
'''
logoFile = "assets/reforged/icon.png"

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"